language: python
python:
  #- 2.6
  - 2.7
env:
  - DJANGO_VERSION="<1.5"
  - DJANGO_VERSION="<1.6"
  - DJANGO_VERSION="<1.7"
  #- DJANGO_VERSION="<1.8"
install:
  - "pip install -q Django$DJANGO_VERSION"
  - "pip install ."
script:
  - python setup.py test
notifications:
  email:
    on_success: change
    on_failure: change
